# Build stage
FROM maven:3-eclipse-temurin-17 AS build

# Set the working directory inside the container
WORKDIR /app

# Copy the Maven project files
COPY pom.xml ./
COPY src ./src

# Build the project and skip tests
RUN mvn clean package -DskipTests

# Runtime stage
FROM eclipse-temurin:17-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the built JAR from the build stage to the runtime stage
COPY --from=build /app/target/BMS-BackEnd*.jar BMS-BackEnd.jar

# Expose the application port
EXPOSE 8080

# Command to run the Spring Boot application
ENTRYPOINT ["java", "-jar", "BMS-BackEnd.jar"]
